#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== OpenAlgo Fleet Manager Setup ==="
echo ""

if [[ -f "$ENV_FILE" ]]; then
    echo "[!] .env already exists at $ENV_FILE"
    echo "    Remove it first if you want to regenerate: rm $ENV_FILE"
    exit 1
fi

FERNET_KEY=$(python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")
SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")

read -rsp "Enter Fleet Admin bootstrap password (empty = no bootstrap): " BOOTSTRAP_PW
echo ""

if [[ -z "$BOOTSTRAP_PW" ]]; then
    echo "[i] No bootstrap password set — first-run wizard will skip."
fi

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh
DATABASE_URL=postgresql+asyncpg://fleetmgr:changeme@localhost:5432/fleetmgr
FERNET_KEY=$FERNET_KEY
SESSION_SECRET=$SESSION_SECRET
FLEET_ADMIN_BOOTSTRAP_PASSWORD=$BOOTSTRAP_PW
SCRIPTS_REF=main
POLL_INTERVAL_SECONDS=60
EOF

echo ""
echo "[✓] .env written to $ENV_FILE"
echo ""
echo "To start:  docker compose up -d"
echo "Then visit: http://localhost:8000"
echo ""
echo "First login:"
if [[ -n "$BOOTSTRAP_PW" ]]; then
    echo "  Username: admin"
    echo "  Password: (the bootstrap password you entered)"
else
    echo "  Register via web UI (first user becomes admin)"
fi
