#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== OpenAlgo Fleet Manager Setup ==="
echo ""

if [[ -f "$ENV_FILE" ]]; then
    echo "[!] .env already exists at $ENV_FILE"
    echo "    Remove it first if you want to regenerate: rm $ENV_FILE"
    exit 1
fi

FERNET_KEY=$(python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")
SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")

read -rsp "Enter Fleet Admin bootstrap password (empty = no bootstrap): " BOOTSTRAP_PW
echo ""

if [[ -z "$BOOTSTRAP_PW" ]]; then
    echo "[i] No bootstrap password set — first-run wizard will skip."
fi

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh
DATABASE_URL=postgresql+asyncpg://fleetmgr:changeme@localhost:5432/fleetmgr
FERNET_KEY=$FERNET_KEY
SESSION_SECRET=$SESSION_SECRET
FLEET_ADMIN_BOOTSTRAP_PASSWORD=$BOOTSTRAP_PW
SCRIPTS_REF=main
POLL_INTERVAL_SECONDS=60
ALERT_WEBHOOK_URL=
# Shared key for /api/partner/* (the simplifyed.in client area). Left empty
# deliberately: a customer-facing surface should be switched on by a decision,
# not by running setup. Fill in with: openssl rand -hex 32
PARTNER_API_KEY=
EOF

echo ""
echo "--- SSH Keypair for Fleet Manager ---"
echo "It is recommended to use a dedicated SSH key for the Fleet Manager."
echo "This key should be added to each managed server's authorized_keys."
read -rp "Generate a dedicated SSH keypair? [Y/n]: " GEN_KEY
if [[ "$GEN_KEY" != "n" && "$GEN_KEY" != "N" ]]; then
    KEY_DIR="$SCRIPT_DIR/ssh-keys"
    mkdir -p "$KEY_DIR"
    ssh-keygen -t ed25519 -f "$KEY_DIR/id_ed25519" -N "" -C "fleet-manager-$(hostname)" -q
    echo ""
    echo "[✓] SSH keypair generated:"
    echo "    Private: $KEY_DIR/id_ed25519"
    echo "    Public:  $KEY_DIR/id_ed25519.pub"
    echo ""
    echo "Add this public key to each server you manage:"
    echo ""
    echo "  ssh-copy-id -i $KEY_DIR/id_ed25519.pub ubuntu@<server-ip>"
    echo ""
    echo "Onboard new servers via the Provisioning Wizard and paste the"
    echo "contents of $KEY_DIR/id_ed25519 as the SSH private key."
fi

echo "[✓] .env written to $ENV_FILE"
echo ""
echo "To start:  docker compose up -d"
echo "Then visit: http://localhost:8000"
echo ""
echo "First login:"
if [[ -n "$BOOTSTRAP_PW" ]]; then
    echo "  Username: admin"
    echo "  Password: (the bootstrap password you entered)"
else
    echo "  Register via web UI (first user becomes admin)"
fi
